apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo
    app.kubernetes.io/part-of: purple-mermaid-app
  name: demo
  namespace: rorai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: demo
    spec:
      containers:
      - image: quay.io/sbudhwar/demo
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: "1"
            memory: 512Mi
status: {}
